### ISSUE TITLE
sucessivas criações de árvore b a partir da ag causa segfault

### ISSUE THREAD

**Issue by simasgrilo** [simasgrilo/EDA-20191#4]
parece ter a ver com o liberaAB não estar 100%. No mínimo, não são liberadas as estruturas internas ao vetor de chaves (a-> figs[i]).

**Comment by simasgrilo** [comment]
se liberar cada a->figs[i], agora dá invalid pointer no free. Sem nada pros filhos, ele da sigsegv dentro do malloc na quarta ou quinta vez.

**Comment by Daniel-02** [comment]
Ajustei o free para percorrer so ate nchaves, e inicializei os ponterios de figs com NULL
